name = "s-op-gungi"
compatibility_date = "2026-07-10"
pages_build_output_dir = "public"

[[kv_namespaces]]
binding = "SOP_STATE"
id = "05ce4e26ad784fde95ecad137c60b2ee"
preview_id = "05ce4e26ad784fde95ecad137c60b2ee"
